import Head from 'next/head'
import Hero from '../components/hero'
import Slider from '../components/slider'
import {SliderData} from '../components/sliderData'

export default function Home() {
  return (
    <>
      <div>
        <Head>
          <title>Photography Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Hero heading='Capture Photography' message='I capture moments in nature and keep them alive.'/>
        <Slider slides={SliderData} />
      </div>
    </>
  )
}
